# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Limitons à une seule version stable de Node.js
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Désactiver le cache temporairement
        # cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Generate package-lock.json
      run: npm i --package-lock-only
    - name: Build
      run: npm run build --if-present
      env:
        # Ajouter les variables d'environnement Sanity
        SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID || 'placeholder-id' }}
        SANITY_DATASET: ${{ secrets.SANITY_DATASET || 'production' }}
